# Generated by Django 2.2.12 on 2021-11-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
    ]
