# Generated by Django 2.2.10 on 2022-04-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='leccion',
            field=models.CharField(default=1, max_length=255, null=True, unique=True),
        ),
    ]
