# Generated by Django 2.2.12 on 2021-09-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0002_auto_20210910_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('respuesta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=255)),
                ('Preguntas', models.CharField(max_length=255)),
                ('calificacion', models.CharField(max_length=255)),
            ],
        ),
    ]
