# Generated by Django 2.2.12 on 2021-11-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0002_auto_20211108_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='leccion',
            field=models.CharField(default=1, max_length=255, null=True),
        ),
    ]
