# Generated by Django 2.2.12 on 2021-11-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0002_auto_20211110_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='correcta',
            field=models.BooleanField(verbose_name='¿Es esta la pregunta correcta?'),
        ),
    ]
