# Generated by Django 2.2.12 on 2021-10-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0003_pregunta_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='Preguntas',
            new_name='respuesta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='leccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
