# Generated by Django 2.2.12 on 2021-11-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0003_auto_20211108_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='leccion',
        ),
    ]
