# Generated by Django 2.2.10 on 2022-03-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0004_auto_20220311_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecciones.Grupo'),
        ),
    ]
