# Generated by Django 2.2.12 on 2021-11-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0004_remove_pregunta_leccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntarespondida',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Puntaje obtenido'),
        ),
    ]
