# Generated by Django 2.2.12 on 2021-10-02 04:28

from django.db import migrations, models
import django.db.models.deletion
import lecciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0004_auto_20211002_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecciones.Usuario'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='leccion',
            field=models.CharField(default=1, max_length=255, verbose_name=lecciones.models.Pregunta),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecciones.Rol'),
        ),
    ]
