# Generated by Django 2.2.12 on 2021-10-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0005_auto_20211002_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='respuesta',
            new_name='respuesta_p',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='Preguntas_k',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecciones.Pregunta'),
        ),
    ]
