# Generated by Django 2.2.12 on 2021-11-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0005_auto_20211109_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Puntaje total'),
        ),
    ]
