# Generated by Django 2.2.12 on 2021-11-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0006_auto_20211109_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntarespondida',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje obtenido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje total'),
        ),
    ]
