# Generated by Django 2.2.10 on 2022-03-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0006_auto_20220311_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
