# Generated by Django 2.2.12 on 2021-11-02 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0007_auto_20211002_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElegirRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?')),
                ('texto', models.TextField(verbose_name='Texto de la respuesta')),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_p',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Maximo PUntaje'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(verbose_name='Texto de la pregunta'),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.AddField(
            model_name='elegirrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='lecciones.Pregunta'),
        ),
    ]
