# Generated by Django 2.2.12 on 2021-11-03 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecciones', '0009_preguntarespondida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='preguntarespondida',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lecciones.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje total'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preguntarespondida',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje obtenido'),
        ),
    ]
