# Generated by Django 2.2.12 on 2021-11-03 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0010_auto_20211103_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='Es esta la respuesta correcta?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje obtenido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecciones.ElegirRespuesta'),
        ),
        migrations.AlterField(
            model_name='preguntarespondida',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='lecciones.ElegirRespuesta'),
        ),
    ]
