# Generated by Django 2.2.12 on 2021-11-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0011_auto_20211109_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntarespondida',
            name='correcta',
            field=models.BooleanField(default=False, null=True, verbose_name='Es esta la respuesta correcta?'),
        ),
    ]
