# Generated by Django 2.2.12 on 2021-11-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0012_auto_20211103_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correcta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puntaje_obtenido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='respuesta',
        ),
    ]
