# Generated by Django 2.2.12 on 2021-11-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0013_auto_20211103_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntarespondida',
            old_name='usuario',
            new_name='quizUser',
        ),
    ]
