# Generated by Django 2.2.12 on 2021-11-04 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0014_auto_20211103_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntarespondida',
            name='respuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='lecciones.ElegirRespuesta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje total'),
        ),
    ]
