# Generated by Django 2.2.12 on 2021-11-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0015_auto_20211104_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje total'),
        ),
    ]
