# Generated by Django 2.2.12 on 2021-11-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0016_auto_20211104_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntarespondida',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje obtenido'),
        ),
        migrations.AlterField(
            model_name='preguntarespondida',
            name='quizUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='lecciones.Usuario'),
        ),
        migrations.AlterField(
            model_name='preguntarespondida',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecciones.ElegirRespuesta'),
        ),
    ]
