# Generated by Django 2.2.12 on 2021-11-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0017_auto_20211104_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
    ]
